### ISSUE TITLE
Extension not working while working on SAP CPI

### ISSUE THREAD

**Issue by konqueeftador** [dbeck121/CPI-Helper-Chrome-Extension#1]
Hi,

it's been a few days since when I open a SAP CPI page (/ itspaces), the extension doesn't work correctly.
To make it work again, I am forced to go to the manage browser extensions section (both Chorme and Micr. Edge), restart the extension and then update the affected web pages.
This problem can occur a couple of times a day, creating inconvenience in using it.

Below some screenshot:

- Extension not working

![image](https://user-images.githubusercontent.com/99017563/152514378-9be1b43d-f4a4-4a8f-ad7b-4f658dd35e7e.png)

- Enabled extension

![image](https://user-images.githubusercontent.com/99017563/152514601-f4817561-f1cb-4151-8549-9c2089865ed7.png)

Have you ever encountered this issue?

Best Regards,

**Comment by dbeck121** [comment]
Hi,

thanks for opening an issue.
This problem is solved in 1.8.1 that is in review by google right now. This might take a few days.

For me, pressing F5 to reload the page helped most of the time.

BR
Dominic

**Comment by konqueeftador** [comment]
> 

Hi Dominic,

thank you for your quick response! I'll wait the new version :)

**Comment by dbeck121** [comment]
And stay tuned for 2.0.0 that is under development right now :)
