### ISSUE TITLE
Print iFlow in pdf or png

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#10]
Is it possible (with correct css) to generate a full screen windows with only the flow to print it or save it like png, could be very useful on documentation - presentation.

Other feature, put a comment on group of elements. (Like post-it) with explains.

**Comment by dbeck121** [comment]
Unfortunately I have no direct access to the underlying javascript. So I do not have a possibility to add comments or sth else. That would be a nice feature.

There are some tools that help with creating documentation like figaf or some community driven.

**Comment by SAPNickYang** [comment]
You could use "CPI Explorer" app developed by Fatih Pense to download iFlow image.
https://apps.microsoft.com/store/detail/cpi-explorer/9PBKK398WW57?hl=en-au&gl=AU
