### ISSUE TITLE
Pretty Print doesn't work in 3.8

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#105]
As far as I can tell, the beautify function of the payload window doesn't work anymore in 3.8. I always get this error: 

`<parsererror xmlns="http://www.w3.org/1999/xhtml" style="display: block; white-space: pre; border: 2px solid #c77; padding: 0 1em 0 1em; margin: 1em; background-color: #fdd; color: black">
  <h3>This page contains the following errors:</h3>
  <div style="font-family:monospace;font-size:12px">error on line 1 at column 18: XML declaration allowed only at the start of the document
</div>
  <h3>Below is a rendering of the page up to the first error.</h3>
</parsererror>`

I didn't have time to analyze it yet. @incpi Do you see the same issue? Might it be related to your changes?

**Comment by dbeck121** [comment]
I thought this was related to my xml but interesting you are facing same issue :-)

**Comment by fippu82** [comment]
I thought the same, but after a week or two I have had many different XMLs and started to believe it's indeed a bug :-)

**Comment by incpi** [comment]
Thank you,
i will check and update it. Let me verify it
