### ISSUE TITLE
UI Bugs + Suggestion

### ISSUE THREAD

**Issue by incpi** [dbeck121/CPI-Helper-Chrome-Extension#107]
Hello 3.8.1 has few Minor UI issues,

- Color of sidebar looks awful under certain scenarios.
- Popup Text is too large then expected on small Screens.( Zoom levels might need or something similar. )

---
Plugin UI (Original Message)
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/87596092/2bd2f2e8-cea6-451e-bb98-4390768c52c0)
I would appreciate it if you could share your feedback on this or any changes that you think are necessary.

**Comment by fippu82** [comment]
Looks good to me. What I probably would change is the two labels for version and id and put the version maybe to the very right of the blue title bar and the ID small to the bottom right (it's unimportant for the user) and no gray background for both.

**Comment by dbeck121** [comment]
looks good! Big improvements to the old UI.... Do you use the fomantic ui css that is already included in CPI Helper?

**Comment by incpi** [comment]
Hello dbeck121, I do agree with fippu82. Can't we ditch the ID? Version needs that I understand. Yes, I built on top of fomantic UI with few additional custom CSS.

**Comment by dbeck121** [comment]
Fine with me

**Comment by dbeck121** [comment]
Would be fine with me. It gives a way better structure.
