### ISSUE TITLE
Trace-Deploy Button

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#11]
Is it possible to put a button with directly activation trace and deploy with single click?

**Comment by robertfels** [comment]
@bdbais This is not quite simple. If a flow was not deployed before, then the trace cannot be activated simultaneously. It can only be activated if the flow has already been deployed.
So, if an old flow is already running with this FlowId, then the trace could be started in parallel.

**Comment by dbeck121** [comment]
I am working on a plugin concept. That might be some use case for it :)
