### ISSUE TITLE
Possible Bug - RunLogs Order in Log Viewer

### ISSUE THREAD

**Issue by CorenTheChosen** [dbeck121/CPI-Helper-Chrome-Extension#110]
First - I love this extension, it has drastically improved my work efficiency.  So, thanks for that. 

Not sure if this is a bug or just some weird interaction I'm not seeing, but when I am in an iflow, I deploy, and I select Messages to view the CPI Helper - Logs pop up.  On the RunLogs tab, the logs are deployed in some pseudo(ish) random order.  I write my iflows so my logs are serialized so if they sorted alphabetically, as they are in the normal CPI log pages, they appear in the order of execution.  I would expect this to also be the case in the helper logs, but it is not.  I haven't seen a pattern, sometimes they are in the correct order, sometimes not.  Sometimes they start in the correct order and then get all messed up a few logs in.   

Thanks,

**Comment by dbeck121** [comment]
The logs are in the order that the CPI returns in their internal API... Let me check if I can order it. I think it was in alphabetical order when I created this feature. CPI helper uses a lot of undocumented APIs so this behaviour can change without notice.

**Comment by dbeck121** [comment]
The logs are in the order that the CPI returns in their internal API... Let me check if I can order it. I think it was in alphabetical order when I created this feature. CPI helper uses a lot of undocumented APIs so this behaviour can change without notice.

Edit: fixed in next release
