### ISSUE TITLE
Retry messages with no logstart and logend does not display in message list while tracing.

### ISSUE THREAD

**Issue by FarihaAli** [dbeck121/CPI-Helper-Chrome-Extension#118]
Hello,

Retry messages with no logstart and logend does not display in message list while tracing.
They are the msgs from JMS queues which shows in MPL and no longer can be retried as queue has been deleted. They just stay there and cannot be retried.

<img width="225" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/24839793/65eac03b-9955-47db-bff1-fc2978767229">

it throws the below error as log start and log end is not present at line 155 of contentscript.
<img width="940" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/24839793/bd8572ab-01e3-4085-97ef-cf0b003c9eba">

**Comment by fippu82** [comment]
Hi, I'm not sure how to reproduce this error. How can you delete a queue when there are still IFlows deployed that use them? It shouldn't be possible.

**Comment by dbeck121** [comment]
Hi,

I think this is more a problem on SAP side and it is too much an edge case, that we spend time here. We are working for free and with limited time so I guess we need to concentrate on other topics. Sorry :-(
