### ISSUE TITLE
Changing button color for the selected entry in Logs window

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#12]
I have enhanced the user interface in Logs window.
The background color of entry that user click will change to a different color.
This will help user to identify which entry is selected when a lots of entries showing in the table.
![2022-06-04_18h03_21](https://user-images.githubusercontent.com/13759617/171990922-64973a96-95d5-4f92-ae69-b4c13024c9e7.gif)

**Comment by dbeck121** [comment]
Nice. It will be available in the next version. 

How do you do the gifs? Seems like sth. how I can improve readme file a lot :)

**Comment by SAPNickYang** [comment]
I use https://www.screenpresso.com/ to record screen and then save the video to gif.
It's as handy as CPI Helper!
