### ISSUE TITLE
Release 3.9.0

### ISSUE THREAD

**Issue by dbeck121** [dbeck121/CPI-Helper-Chrome-Extension#122]
Hi,

release 3.9.0 is planned for next week. 
@incpi and @fippu82: Thanks four your great contributions. If you want, have a quick check if everything works and add your work to whats new in readme and if you want in whats new popup :-)

It is a pleasure to work with you!

BR
Dominic

**Comment by fippu82** [comment]
Thanks @dbeck121, looks all good to me. And I don't have to be mentioned this time. :-) Thanks for releasing!
