### ISSUE TITLE
Zoom not working, CPI settings set to 100% but Integration suite still shown in small font.

### ISSUE THREAD

**Issue by manish-kn** [dbeck121/CPI-Helper-Chrome-Extension#125]
Version 3.9.0
Browser: Chrome Version 120.0.6099.110 (Official Build) (64-bit)

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/67371759/8bec563f-24a5-4826-8ce2-ebc01165f343)

**Comment by dbeck121** [comment]
@incpi could that relate to your UI changes?

**Comment by incpi** [comment]
Hi,

Zoom level effect popup window. It won't change the SAP CPI site. For that browser settings have to change.

Feature:
The small screen popup was too large. To manage that zoom level inserted.

Hope this will help

Keep this open for users to know

Thanks,
Omkar

**Comment by manish-kn** [comment]
In browser the zoon is set to 100%

View without CPI helper (DISABLED extension):
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/67371759/4ce21312-d26d-4438-8cac-556a83bfcd03)

View when CPI helper is active:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/67371759/c60087b1-71a8-44df-a3a1-2bb51b6db021)

**Comment by manish-kn** [comment]
@dbeck121 @incpi : additional information, our whole team is facing the same issue. Seems not just me :)

**Comment by dbeck121** [comment]
@manish-kn we are working on it :)

**Comment by incpi** [comment]
Hello @dbeck121 ,

Issue with Fomantic ui 2.9.3, it's changed font size 531 line.

Thanks,
Omkar

**Comment by dbeck121** [comment]
@incpi that was fast... thanks! I think in general I should delete everything from fomantic ui that is not related to ui class in order to have no interference? what do you think? you are way more into the frontend topics than I am.

**Comment by incpi** [comment]
Hello dbeck121 ,

I don't know what kind of dependency they added in Fomantic.  So i removed necessary lines. Css is too complex to know what will affect what in such a large library.

Thanks,
Omkar

**Comment by manish-kn** [comment]
Hello @dbeck121 / @incpi,
Thanks for the quick fix. When can we expect the update in chrome web store?
I assume - since it affects everyone, should be bit urgent.

**Comment by dbeck121** [comment]
@manish-kn CPI Helper is free and open source and we are working on this project in our free time. So there is no service level here. 
Nevertheless thanks to @incpi it is fixed and I pushed it to the Chrome Store. Chrome store takes 0,5-3 days to check the plugin and after it, it will be released and Chrome updates it automatically.
Of course you are invited to join as a tester. 

@fippu82 created a Discord Channel https://discord.com/invite/Bum4SRMN
@incpi also interesting for you

**Comment by dbeck121** [comment]
@manish-kn good news, Google was fast this time. please check if it updates to 3.9.2 and check if zoom is back to normal.

**Comment by manish-kn** [comment]
@dbeck121  Thanks for you blazing fast support!! :)
The extension is updated and everything is back to normal now!!


![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/67371759/57625437-192b-423d-882b-5cbc91a8c963)
