### ISSUE TITLE
Wrong date & time in Logs window

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#13]
The date & time of entries showing in the Logs table doesn't match to the time period that I select in the from and to fields.
<img width="137" alt="image" src="https://user-images.githubusercontent.com/13759617/171991189-3f738bff-4c28-4727-8280-92d51e898a70.png">
My local timezone is GMT+10 (Melbourne/Australia)
I can see it has 10 hours difference between the time I select in "From" field and time showing in the entries.
My finding is the program uses the date&time from screen without converting it to UTC time in calling API .
I have fixed this and modified the operator when comparing the date time from gt to ge and lt to le to match the meaning "From".
![2022-06-04_18h31_13](https://user-images.githubusercontent.com/13759617/171991531-3945d7dd-5678-49c6-9026-0cd3e0647ac2.gif)

**Comment by dbeck121** [comment]
Pulled to dev branch. Will be available with 2.1.2.
