### ISSUE TITLE
Settings Option for Plugins

### ISSUE THREAD

**Issue by DevGregor** [dbeck121/CPI-Helper-Chrome-Extension#130]
If you write a plugin and add the icon via settings and nothing else‚ it will create a settings pane although the image has (or rather should have) nothing to do with it.

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/477b34f6-d1c8-416b-9ad7-d4e993a3384c)
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/144adc01-0023-4099-9787-607a250938fe)

**Comment by incpi** [comment]
Noted! empty pane will be removed if nothing is present.
Will be fixed in next PR.

 Thanks.
