### ISSUE TITLE
Timeline Plugin - Icon causing trouble with onClick function

### ISSUE THREAD

**Issue by DevGregor** [dbeck121/CPI-Helper-Chrome-Extension#134]
I pulled the newest version and tested the Timeline Plugin. I have noticed that apparently the onClick function is not executed when the icon is clicked in the sidebar.

Only if I hover on the edge of that field it seems to be executed. Otherwise nothing happens.

You can see that in the console as well:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/996f521b-66d8-4ccc-b23b-e36dec2f0b51)

If you try to repeat that you have to make sure that the cursor is looking like this when hovering over the edge or it will not execute the function:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/937fd1f3-a6a3-4b7e-88e7-bac386f9637c)

**Comment by incpi** [comment]
Thanks it'll be fix in next updates !
