### ISSUE TITLE
Limiting height of entry list to avoid scrolling top and down when selecting entry at the bottom

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#14]
When there are many messages and I am selecting entries at the bottom of the list in Logs window.
I need to scroll top and down to see information, like below video.
![2022-06-04_21h35_38](https://user-images.githubusercontent.com/13759617/171997343-7a88e494-31ec-44a2-9f45-9a26069a47dc.gif)

In order to be able to select entries in lower position and still be able to switch tabs quickly.
I limited the height of the list and this could let you select entries in lower position and select its tabs without scrolling up&down.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/13759617/171997362-e999272d-4166-409f-96a5-f37b4bd386e6.png">

**Comment by dbeck121** [comment]
Pulled to dev branch. Will be available with 2.1.2.
