### ISSUE TITLE
Problem while catching X-CSRF-Token - Error in SAP CPI-Helper

### ISSUE THREAD

**Issue by smfabdelrahman** [dbeck121/CPI-Helper-Chrome-Extension#143]
Ive been getting this error since last week. I uninstalled and resinstalled, logged out and in again, but still the same.

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/164879653/a1dc5ab3-7a47-4ef3-82ea-13f460efb212)

**Comment by dbeck121** [comment]
Hi, 

Thanks for opening this issue. I can not reproduce it on my Cloud Foundry tenant.

Could you send me some information that might help like the Datacenter of your tenant, browser that you are using and browser language.

Ideal would be the url of your tenant but of course without the identifier in the beginning like
https://xxxxxxxxxx.integrationsuite.cfapps.us10-002.hana.ondemand.com/

Does that problem occur on all iflows?

Thanks for your help
BR
Dominic

**Comment by dbeck121** [comment]
No more interaction. Will close.

**Comment by jonprow** [comment]
I think the issue is related to the integration being API vs IFlow
