### ISSUE TITLE
Helper loading messages, even if "classic" message log view is opened

### ISSUE THREAD

**Issue by DennisSentler** [dbeck121/CPI-Helper-Chrome-Extension#146]
Hi, 

I have noticed that when you open the classic message log view provided by SAP for a trace, a logon window like the following appears:
![Screenshot 2024-04-01 13 25 48](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/27735947/018f648d-d2fa-4fb9-9192-8ea8f39d346b)

This window appears several times, even if you simply cancel it, it will appear again. 

In the browser log, I have noticed that the helper is trying to retrieve the logs with an incorrectly constructed URL.
**My browsers** URL for a specific trace log:
`https://xxx.hana.ondemand.com/itspaces/shell/monitoring/MessageProcessingRun/{"parentContext":{"MessageMonitor":{"artifactKey":"__ALL__MESSAGE_PROVIDER","artifactName":"All Artifacts"}},"messageProcessingLog":"AGYKmTz5WeMa4GFN5jNSrXQYRXNm","RunId":"AGYKmTwvFfvLR-d9t_VdDrrNN6Y2"}`

**The helper** in the meantime is trying to pull logs from this URL:
`https://xxx.hana.ondemand.com/odata/api/v1/MessageProcessingLogs?$filter=IntegrationFlowName eq 'itspaces/shell/monitoring/MessageProcessingRun/{"parentContext":{"MessageMonitor":{"artifactKey":"__ALL__MESSAGE_PROVIDER","artifactName":"All Artifacts"}},"messageProcessingLog":"AGYKmTz5WeMa4GFN5jNSrXQYRXNm","RunId":"AGYKmTwvFfvLR-d9t_VdDrrNN6Y2"}' and Status ne 'RETRY' and Status ne 'DISCARDED'&$top=20&$format=json&$orderby=LogEnd desc`
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/27735947/cd6f1f8e-760d-486f-ae5d-a0d1ec4df894)

So in my opinion it is an incorrect URL constructed by the helper. There is no iFlow called like this, which of course leads to a 404 error. Also, no logs need to be retrieved for the helper at all, as the user is already working in a monitoring view. 
And this only happens when I cancel the previously opened login window, so I assume this is somehow related. 

I hope this helps with the investigation and can be resolved. If you have any questions, let me know.

BR Dennis

**Comment by incpi** [comment]
Yes, correctly I am facing the same issue. Btw we don't need a popup on this page...

**Comment by fippu82** [comment]
I can't reproduce it. The "itspaces" URL is something that only exists on Neo environment. @DennisSentler are you on Neo or CF?

**Comment by DennisSentler** [comment]
thank you, guys.

@incpi for me, this happens on either way, but not on the "normal" Integration Suite UI. 

@fippu82 yes, you're right, if I access the monitoring through the Integration Suite system URL, it is not a problem. 
I am not using the neo environment, but instead of working with the Integration Suite UI, I access the cloud integration application through a dedicated (CI only, no API M ..) UI and URL. 
Integration Suite UI: 
`https://xxxx.integrationsuite.cfapps.eu10-002.hana.ondemand.com/shell/monitoring/MessageProcessingRun/...`
CI Standalone UI: 
`https://xxxx.it-cpi024.cfapps.eu10-002.hana.ondemand.com/itspaces/shell/monitoring/MessageProcessingRun/...`

The CI standalone UI is not cluttered with all the other integration suite applications and is faster to load and navigate. But it seems that it has the "itspaces" url part. 
BTW for every Integration Suite, the CI Standalone URL will be different, because it does contain tenant specific information, like "cpi-024".., which will differ from tenant to tentant.

**Comment by fippu82** [comment]
@DennisSentler, thanks for the information. Ah, you're right, itspaces is not (only) Neo, but the non-IS URL. We had similar issues with the two different types of URLs before, right @dbeck121 ? This should be handled somewhere in the code. We will have to look into this.

**Comment by fippu82** [comment]
But actually @incpi is right that we should simply avoid showing the popup on this page, then the problem should also be solved.

**Comment by dbeck121** [comment]
I agree with you. To be honest, I do not really understand, why the popup is shown. It should detect from the url that it should disappear.

**Comment by fippu82** [comment]
Yes, it's probably a bug in the handleUrlChange() function of contentScript.js. It was changed a while ago as I can see.

**Comment by incpi** [comment]
Hello,
I don't use CI, but for me neo and CF are working. Please verify after new PR.
Thanks, 
Omkar

**Comment by dbeck121** [comment]
@incpi you are genious :-)

**Comment by fippu82** [comment]
@dbeck121 This issue can be closed. I just tested it successfully as well.
