### ISSUE TITLE
Content Enricher Step not colored red in trace

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#149]
The Content Enricher Step is not colored red in inline trace in case of an error in this step. First assumption is that it happens because the step creates four entries in the trace (although that's true for https and other steps too):

SAP original trace view: 

![2024-04-10 10_34_50-shell_monitoring_MessageProcessingRun_%7B%22parentContext%22_%7B%22MessageMonito](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/14195212/8c22cca0-1b5c-4228-84f5-3ef47a7923e9)

Inline Trace doesn't show any error (nothing colored in red despite an error):

![2024-04-10 10_40_10-IF_RHENUS_GET_PACKAGE_PDF DEV](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/14195212/08cbe8f2-e453-42ae-b1e9-075c74402d82)

**Comment by dbeck121** [comment]
Interesting... I will have a look

**Comment by dbeck121** [comment]
fixed in last commit.

**Comment by dbeck121** [comment]
![CleanShot 2024-04-14 at 18 07 46@2x](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/54773577/0299a5f6-21fb-4993-b7d1-8ecb193fb845)

**Comment by dbeck121** [comment]
![CleanShot 2024-04-14 at 18 07 46@2x](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/54773577/590f69c9-8aae-4702-b599-a7ab8d62b615)

seems like it is not collecting information about the odata call... so it will not show the arrow between receiver and content enricher

**Comment by fippu82** [comment]
Perfect, thanks for your work!
