### ISSUE TITLE
Idea: Provide search help for "credential name"

### ISSUE THREAD

**Issue by gregorwolf** [dbeck121/CPI-Helper-Chrome-Extension#151]
Hello CPI Helper Team,

would it be possible to provide the feature requested in the SAP Influencing request [320780 - "credential name" in auth. details as select field, no more free text](https://influence.sap.com/sap/ino/#idea/320780)?

CU
Gregor

**Comment by dbeck121** [comment]
I like the idea. It should be internally an api call with

await makeCallPromiseXHR("GET", "/" + cpiData.urlExtension + "odata/api/v1/UserCredentials",.... There it is possible to collect all security artifacts. Then there needs to be a dropdown injected.

Will put it in the backlog.

**Comment by DevGregor** [comment]
Hey @gregorwolf
This is Gregor (as well) :)

I really like this idea and I have made a first version of it. There are still some tweaks and things that need improvement but I think this can be used for a rough implementation (#169). Feel free to check it out!

**Comment by dbeck121** [comment]
Successfully finished :)

@gregorwolf
