### ISSUE TITLE
[Issue] Chrome closes when coping payload

### ISSUE THREAD

**Issue by metainit** [dbeck121/CPI-Helper-Chrome-Extension#156]
Navigator closes unexpectedly when coping any payload from trace view either using copy button or using Ctrl+C.

**Comment by dbeck121** [comment]
Hi,

unfortunately I can not reproduce the issue. Can you give more information if you see an error message and which browser / CI tenant you use (neo or CF)?

**Comment by metainit** [comment]
Hello @dbeck121, I've noticed it only happens with really large payloads. 
In normal situations it doesn't happen.

Additionally, I can tell you my tenant is CF and the browser is Chrome. I haven't seen the crash dumps but I think it has to do with memory dump.

**Comment by dbeck121** [comment]
@metainit what size are we talking about? :-)

**Comment by metainit** [comment]
It was a 25MB text plain file.

**Comment by bdbais** [comment]
25 MB is maximun payload you can ask to Integration Suite trace / log.
Never happend to me, could you send Chrome version and system information (memory used)

**Comment by dbeck121** [comment]
I can not reproduce the issue with CF and 25MB Payloads. Copy works for me. Maybe fixed by accident :-)
