### ISSUE TITLE
Beautify does not work when accessing payload in log/persist tab

### ISSUE THREAD

**Issue by emilehermans** [dbeck121/CPI-Helper-Chrome-Extension#157]
When accessing log and you want to view the payload of the persisted messages, the beautify functionality does not work for me.
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/45028434/81a444f9-41da-4b5e-9bf2-61e5867db31c)

The Above message is a simple json message.

**Comment by incpi** [comment]
Hello @emilehermans ,

- Only reason that can happen is if JSON payload has data/format issues. It will give you non formatted data. else it will be as below.
See, My JSON sample if it's correct it will display correct one.

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/87596092/42409500-ea11-4660-a7b4-11acf64ea2d4)


Thanks,
Omkar

**Comment by emilehermans** [comment]
When I use Beautify in trace mode this works fine:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/45028434/f50530eb-46eb-4508-8065-10b2e0a191ab)

However when using beautify on the same payload in the log/persist tab it does not work:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/45028434/cc6fd49c-7c7b-4e06-8bb5-4183120997b6)

I tried to figure out why it behaves like this but had no success till now.

**Comment by dbeck121** [comment]
works for me too.... very strange. Can you somehow try to copy the payload and create a minimal example?

timer --> content modifier with message body --> persist --> end

if this still can not be beautified, it must have sth to do with message content

**Comment by incpi** [comment]
Hello @emilehermans, 

Long time for this thread but i would like to confirm one thing, 

Which environment you tenant is hosted? - CF or NEO

Thanks
Omkar

**Comment by incpi** [comment]
Thanks a lot. It was unnoticed till today. I haven't analyzed it yet but neo has issues It not working with no error logs. (Button doesn't do anything)

**Comment by dbeck121** [comment]
> Beautify issue on NEO environment is still there when viewing in log-persist tab, also for xml payloads. Is there a specific reason this is not possible at the moment?

We work on it here in our free time. There are a few critical bugs at the moment and so probably nobody has time to work on them. Unfortunately there are no SLAs. Sorry. But I have it on the screen.

**Comment by emilehermans** [comment]
No worries. I was just curious. I didn’t find time to dive into it myself. Thanks for your reply.
