### ISSUE TITLE
CPI helper Sidebar not loading message logs for some iflows

### ISSUE THREAD

**Issue by hashrw1** [dbeck121/CPI-Helper-Chrome-Extension#158]
Hi @dbeck121,
on SAP CPI CF, for some iflow messages are often not shown in sidebar, their logs never appear. Below you can check tow examples:

<img width="809" alt="Screenshot_2" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/164931971/d95879c7-5c52-493c-b08a-b383847d88e0">
<img width="499" alt="Screenshot_3" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/164931971/ec63d9f8-6f07-42d7-9277-3fec28812e2a">

This issue occurs from the last week. Could you please check this and give support ?

Thank you in advance!

**Comment by dbeck121** [comment]
@hashrw1 I will check. Thanks for the issue.

Something special with these flows? All with JMS adapter for example? Do you run on CF or Neo?

**Comment by fippu82** [comment]
@hashrw1 Does this happen all the times for certain Iflows, or only occasionally? If all the time, would you mind sending me the Iflow where you see this error? You could upload the zip file here as attachment to your response.

**Comment by hashrw1** [comment]
> @hashrw1 I will check. Thanks for the issue.
> 
> Something special with these flows? All with JMS adapter for example? Do you run on CF or Neo?

Hi @dbeck121  , this issue happens all the time for certain iflows with JMS adapter, running on CF. Best regards.

**Comment by hashrw1** [comment]
> @hashrw1 Does this happen all the times for certain Iflows, or only occasionally? If all the time, would you mind sending me the Iflow where you see this error? You could upload the zip file here as attachment to your response.

Hi @

> @hashrw1 I will check. Thanks for the issue.
> 
> Something special with these flows? All with JMS adapter for example? Do you run on CF or Neo?

Hi @dbeck121 @fippu82 , this issue happens for certain iflows with JMS adapters, running on CF. I cannot attach the zip due to customer restrictions. The plugin does not show any message trace for these iflows. 

Best regards.

**Comment by fippu82** [comment]
@hashrw1 What about the standard logs and the trace page (of CPI Monitoring). How do they look like in this case? 
Also, if you could reproduce the issue in a modified version of your Iflow, that you are allowed to share, that would be great. Otherwise, I don't know how to reproduce it with the given information.

**Comment by dbeck121** [comment]
No new comments since May... will close
