### ISSUE TITLE
Bugged Text, Button and Icon Coloring

### ISSUE THREAD

**Issue by DevGregor** [dbeck121/CPI-Helper-Chrome-Extension#178]
**Describe the bug**
Some coloring needs to be fixed in the upcoming version (4.0.0).

**To Reproduce**
1. Install CPI Helper (4.0.0)
2. Check Message Sidebar and Whats New Popup

**Expected behavior**
Some text, labels and icons are not visible unless highlighted or hovered.

**Screenshots**
Current look:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/89554d06-f780-4cd7-9f31-61ef5368f676)
Highlighted:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/976cffca-0801-46aa-90b3-bb8afa7f1100)

Current look:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/2b875115-b960-4b01-9e59-1826c655e3c6)
Hovered:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/907444fc-1bb9-43d7-9882-caafaccb736b)
Hovered:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/87228ed4-0f83-410e-bf86-dba4ded0d11d)
Clicked:
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/8744c657-f36a-42d8-bb8a-00b32e523de8)

**Version**
4.0.0

**Desktop:**
 - OS: Windows 11
 - Browser: chrome
 - Version: 125.0.6422.113

**Tenant type:**
 - Cloud Floundry
 - Neo

**Additional Info:**
The browseraddon Dark CPI was turned off when checking this just to make sure this wasn't caused by it since some other coloring issues are affected by that addon. Posted issue there as well: https://github.com/incpi/Dark-CPI-Web-Extension/issues/5

**Comment by incpi** [comment]
Hello @DevGregor,
@dbeck121 This might need your attention.

for as I mentioned earlier (Solution looks simple yet complex), 

1. Fomantic UI issue: This is going to big change may be as if SAP Officially or with plugin Dark CPI support dark-theme then our Fomantic UI is not ready to use in dark mode. 

2. SAP Theme support: SAP theme also handling few colors in CPI helper, we need to modify with **extensive** CSS.

Hope this explanation helps.
Omkar

**Comment by DevGregor** [comment]
I finally understand a bit more what the issue here is. By default we have a white background and white text but if I choose a color the aforementioned color issues are "fixed":
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/77123831/eb50971f-c277-4bcd-bcf5-bb3960b60399)

**Comment by dbeck121** [comment]
Thanks! Super nice how fast you are! Amazing to work with you!
