### ISSUE TITLE
REST API : not present on Message window

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#19]
Hi, we are using new "REST API" type of Flow and we notice it's not present on CPI Helper list of artifacts to debug.

**Comment by SAPNickYang** [comment]
@dbeck121 I am implementing this enhancement.
Will create a pull request when it's done.
Cheers.

Regards,
Nick

**Comment by dbeck121** [comment]
nice. We will see this in the next version then :-)

**Comment by SAPNickYang** [comment]
@dbeck121 
I saw your whatsNew.js for 2.3.0
It only mentioned "REST API" but actual the enhancement includes REST API and SOAP API two types of iFlow.
<li>Version 2.3.0: Works now with "Rest API" Iflow type</li> 
Cheers.

Regards,
Nick
