### ISSUE TITLE
[Bug]: Ram goes up on edge when i access "Assess Migration Scenarios"

### ISSUE THREAD

**Issue by Lunahri17** [dbeck121/CPI-Helper-Chrome-Extension#192]
**Describe the bug**
When i enter Assess Migration Scenarios on cpi the ram on Microsoft edge goes up to 20gb on my pc an then the tab crash. I tested on firefox and this doesn't happend.

**To Reproduce**
1. Enable the extension "CPI Helper".
2. Go to Integration Suit.
3. On "Home" scroll down to the "Capabilities" section.
4. Click on "Create Requests" on "Assess Migration Scenarios" Box.
5. And after a few second, you will se on the task manager how the ram consumtion of Edge goes up.

**Expected behavior**
The ram consumtion stays the same or goes up a little bit.

**Screenshots**
Video: [Youtube Video](https://www.youtube.com/watch?v=wjGkkZK_rEI)

**Version**
3.14.1
With this plugins enabled:
 - Simple Reference (Beta)
 - undeploy plugin
 - Apache Camel Update Message Remover

**Desktop:**
 - OS: Windows 10 22H2
 - Browser Edge
 - Version 126.0.2592.113 (Official build) (64-bit)

**Tenant type:**
 - Cloud Floundry

**Comment by dbeck121** [comment]
Hi @Lunahri17,

probably the best bug description so far :-) I appreciate the video.

Unfortunately I am on mac and at least on Chrome it does not have the same effect. Does anyone have the same issue?

Might I ask you to test some things:
- Just in case you have Chrome installed: Could you test it with Chrome, as Chrome and Edge share the same engine. 
- Another Idea would be to check if there are some useful console logs in the developer tools. So maybe you can press F12 before clicking on Assess Migration Scenarios. Maybe the console tab gives us a hint
- Could you disable Apache Camel Update Message Remover and try again?

**Comment by Lunahri17** [comment]
Srry, this is the first time i do an issue on github haha.

@dbeck121 i tryed disabling one by one the plugins i have enabled, but that doesn't work.

I wil try the other to options. Thanks!

**Comment by Lunahri17** [comment]
in the console of edge doesn't say too much i think:
![image](https://github.com/user-attachments/assets/bd6d8df5-a851-4ac1-b7f7-2ce2322f8b0f)

But on the memory tab i see this:
![image](https://github.com/user-attachments/assets/43593202-da7b-494e-b3f8-959ded0a9e56)

This is a trial account so i can share anything with any problem if you want.

**Comment by Lunahri17** [comment]
Chrome has the same behavior.

**Comment by dbeck121** [comment]
Ok I think we know at least what causes the issue and I pushed 3.14.2 to the stores. 

@Lunahri17 : This helped a lot. Thank you so much!

**Comment by Lunahri17** [comment]
Okey @dbeck121!! thanks for the support nwn

**Comment by Lunahri17** [comment]
i think the bug is fixed! thanks!!

**Comment by dbeck121** [comment]
Thanks @Lunahri17 for your issue and your great help!
