### ISSUE TITLE
[Bug]: CPI-Helper not working in REST-API and ODATA

### ISSUE THREAD

**Issue by dbeck121** [dbeck121/CPI-Helper-Chrome-Extension#205]
**Describe the bug**
Trace, Message.... etc. do not work anymore since 3.15. for REST and ODATA Artifacts

**Screenshots**
![image](https://github.com/user-attachments/assets/0c931737-33b0-4874-93bb-a97f96dd8f5b)

**Version**
3.15.x

**Desktop (please complete the following information):**
Chrome

**Tenant type (please complete the following information):**
CF

**Comment by incpi** [comment]
Sorry, I thought SAP change API artifact So added label, but it was due to our code. Fixed in content script. Fixed now

Thanks

**Comment by shajipapn** [comment]
Hi @dbeck121 / @incpi , same issues for me. I reported and noticed it's been reported.
Is there a fix for this?

**Comment by dbeck121** [comment]
Yes, new version coming soon!

**Comment by dbeck121** [comment]
Released
