### ISSUE TITLE
[Other]: Want to create a plugin but can't make external requests

### ISSUE THREAD

**Issue by cybertheory** [dbeck121/CPI-Helper-Chrome-Extension#206]
Hey,
  I want to create a plugin for a tool I am making that makes a post request to an external API. I see in your guidelines you don't allow this. If I can prove via my code I am only submitting voluntary inputs from the user, can you allow this? Would love to discuss this more, and if needed can hop on a call. Thank you!

**Comment by dbeck121** [comment]
Hi @cybertheory,

Can you explain more about the api you will call and purpose of the plugin? I think in general this might be possible.

**Comment by cybertheory** [comment]
Hi, thank you! May we take this conversation private over email or something similar? The concept is still in early stages.

**Comment by dbeck121** [comment]
@cybertheory 

Can you add me on LinkedIn or send me an email to cpihelper@kangoolutions.com?
