### ISSUE TITLE
[Bug]: Fail when try to increase the last execution > 10

### ISSUE THREAD

**Issue by tuliovargas** [dbeck121/CPI-Helper-Chrome-Extension#207]
**Describe the bug**  
When attempting to increase the "No. of Last Execution" value beyond 10, the plugin does not display more than 10 executions. Reducing the number of last executions works as expected, but any attempt to set the value above 10 fails to show more than 10 executions.

**To Reproduce**  
1. Go to 'Settings'
2. Click on 'No. of Last Execution'
3. Increase the value to more than "10"
4. Observe that the list of executions does not reflect the increase beyond 10

**Expected behavior**  
The system should display the exact number of last executions as set in the "No. of Last Execution" field, even when the number is greater than 10.

**Version**  
v3.15.2

**Desktop (please complete the following information):**
- OS: Win11  
- Browser: Chrome  
- Version: 128.0.6613.138 (Official Build) (64-bit)

**Tenant type (please complete the following information):**
- Cloud Foundry / Multicloud

**Comment by dbeck121** [comment]
Solved. Check https://github.com/dbeck121/CPI-Helper-Chrome-Extension/issues/208

**Comment by tuliovargas** [comment]
Hi @dbeck121 , thanks for your quiclkly response, but it still not working from my side, please have a look:

![plugin__ezgif-3-2a74def528](https://github.com/user-attachments/assets/3694f085-49a9-4760-a97f-73bb4afe8d1a)

**Comment by incpi** [comment]
This is not fixed

**Comment by dbeck121** [comment]
@tuliovargas sorry, my fault. I mixed things up. I will mark this issue with next release so that we fix it asap

**Comment by tuliovargas** [comment]
No worries @dbeck121 
you're doing a great job; well done for this wonderful plugin :)

**Comment by dbeck121** [comment]
new version pushed to stores!
