### ISSUE TITLE
CPI Helper not working in REST API Iflows since last week 

### ISSUE THREAD

**Issue by shajipapn** [dbeck121/CPI-Helper-Chrome-Extension#208]
Bug

It seems the trace is not getting activate for REST API flows since last week. In integration flows it's working fine.
Is it only for me or for everyone? Am i missing some config for REST API flows?

This was started from last week. till then  it was working fine.

Please suggest.

Jakku

1- Go to CPI inetgration suite (Designs- Integrations-Add- Add REST API-create an iflow with REST API - save and deploy)
1. Go to trace
3- expecting the CPI helper options should be available 
2. then Clicked on CPI hepler
3. Nothing is showing

Expected behavior
CPI hepler traces should be able to view on REST API.ODATAAPI and integration flows too,

**Screenshots**
screenshot Added

**Version**
Edge - Version 128.0.2739.79 (Official build) (64-bit)

**Desktop (please complete the following information):**
 - OS: [windows qq]
 - Browser [Version 128.0.2739.79 (Official build) (64-bit)
 - Version [Version 128.0.2739.79 ]
 
 Tried with firfox too but same error.

**Tenant type (please complete the following information):**
Multicloud

Please suggest.

<img width="941" alt="1" src="https://github.com/user-attachments/assets/3b8772d3-0a15-4fb8-96ee-cab4a5a66755">
<img width="800" alt="2" src="https://github.com/user-attachments/assets/52d03f98-94f4-42a5-ba1d-24e4665659f1">

**Comment by IntUser13** [comment]
Hi All,

I am also facing the same issue since last week. Tried on multiple browsers(Edge, Chrome and Firefox) but the CPI Helper button doesn't show up(Below the Edit/Configure buttons in IFlow). 

Would be great if there is a workaround to enable it for the time being.

**Comment by incpi** [comment]
please see issue: #207 
already fix in dev.
Thanks

**Comment by shajipapn** [comment]
HI @IntUser13 . Mine seems a duplicate query. the same query raised here.
@incpi , is there any workaround 

https://github.com/dbeck121/CPI-Helper-Chrome-Extension/issues/205

Regards
Jakku

**Comment by shajipapn** [comment]
> please see issue: #205 already fix in dev. Thanks

Thanks @incpi , do I need to wait till prod release, or do I need to make any manual change in my plugin ?

Regards
Jakku

**Comment by IntUser13** [comment]
Thanks @incpi and @shajipapn for the update.

**Comment by IntUser13** [comment]
Thanks @dbeck121 and @incpi for the quick fix . 
Appreciate the great work you guys have been doing!

**Comment by shajipapn** [comment]
WoW super. thanks @dbeck121 @incpi. the tool is a great saver. thanks for all your effort.

**Comment by dbeck121** [comment]
Version released. Will close here

**Comment by shajipapn** [comment]
Hi @dbeck121 
The trace's are not available yet. Do I need to wait for _sometime_ to get it reflected?

**Comment by shajipapn** [comment]
seems okay in Firefox but still not showing up in edge. let me check it tomorrow too thanks @dbeck121

**Comment by incpi** [comment]
> seems okay in Firefox but still not showing up in edge. let me check it tomorrow too thanks @dbeck121 

Hey, do not need daily  updates. 
From my experience, edge at least take a week to reflect. So i hope you wait for a week from release date

Thank you

**Comment by shajipapn** [comment]
cool. no worries.
