### ISSUE TITLE
[Bug]: Error activating Trace

### ISSUE THREAD

**Issue by vonrar** [dbeck121/CPI-Helper-Chrome-Extension#239]
I'm getting the error 'Error activating trace in Cloud Integration'

**Steps to reproduce the behavior:**
1. Pick any iflow
2. Click trace
3. error appears

**Expected behavior**
Trace should be activated

**Screenshots**
![imagen](https://github.com/user-attachments/assets/dbc52ef6-8d7e-47db-9842-dea6cf69608f)
![imagen](https://github.com/user-attachments/assets/f9a44e61-cea9-4371-bc0a-2eda6083e227)

**Version**
3.16.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 131.0.2903.51

**Tenant type (please complete the following information):**
 - Cloud Floundry/ Multicloud

**Additional context**
Also having the same problem in Firefox with extension version 3.17.0

**Comment by Incpi** [comment]
Hello,
I already mention cause #238. Will be Fixed soon.

Thank you for letting us know.

**Comment by dbeck121** [comment]
@vonrar can you check if it is fixed with released 3.17?

**Comment by vonrar** [comment]
I'm afraid it's still broken, 
![imagen](https://github.com/user-attachments/assets/e94e7362-c93e-4c3c-ba4e-b34909d8dc1d)

![imagen](https://github.com/user-attachments/assets/c9db0eaa-7ee8-477f-aa54-294d7bb9c050)

**Comment by fippu82** [comment]
I just checked. It doesn't work on CPI tenants which have an active Edge Cell. Otherwise it works. 
My fix above fixes this for the Edge cell cases.
