### ISSUE TITLE
Undeploy button doesn't respect the AccessPolicies

### ISSUE THREAD

**Issue by GLesieurCascades** [dbeck121/CPI-Helper-Chrome-Extension#24]
Using the CPI Helper plugin, a developper is able to undeploy an artifact even when the Access Policy should restrict that action.
Using the normal way, it prevent undeploying the artifact

**Comment by dbeck121** [comment]
:-) that seams to be a bug in SAP and not in CPI Helper. Do you have the option to open a ticket with SAP?

**Comment by dbeck121** [comment]
No response...
