### ISSUE TITLE
[Bug]: Inline Trace Beautify feature not working anymore in Firefox

### ISSUE THREAD

**Issue by Weetabeex** [dbeck121/CPI-Helper-Chrome-Extension#240]
**Describe the bug**
It is not possible anymore to beautify XML body in an Inline Trace message.

**To Reproduce**
1. Activate a trace
2. Log a message with this trace
3. Activate the inline trace
4. Open an inline trace message by double-clicking on it
5. Go to the body tab
6. Click on Beautify
7. The XML body disappears

**Expected behavior**
The XML body should be beautified

**Screenshots**

![Screenshot 2024-11-22 161052](https://github.com/user-attachments/assets/8dfe5073-1430-4cd8-9a36-eb7d94600559)

**Version**
3.17.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: FIREFOX
 - Version: 132.0.2 (64-bit)

**Tenant type (please complete the following information):**
 N/A

**Additional context**

**Comment by dbeck121** [comment]
@Weetabeex 
Thanks for the issue. We will check this!

**Comment by dbeck121** [comment]
@Weetabeex: I can not really reproduce your issue. Works fine for me. We have a fix for logs and beautify in neo. Maybe it is related. Weill be fixed with next update.

**Comment by dbeck121** [comment]
@Weetabeex: sorry! I can now reproduce.

**Comment by dbeck121** [comment]
@Weetabeex pushed a fix. Maybe this works in next release then.
