### ISSUE TITLE
[Bug]: com.sap.it.op.srv.web.cf.RuntimeLocationListCommand 501 (Not Implemented)

### ISSUE THREAD

**Issue by neooblaster** [dbeck121/CPI-Helper-Chrome-Extension#245]
Hi Team.

Please find below an issue that occurs since update to 3.17.1.

**Describe the bug**
Since the update from 3.17.0 to 3.17.1 of plugin, I get the following error which run in infinite loop : 

CPI-Helper has run into a problem while loading data :

![image](https://github.com/user-attachments/assets/124954c5-be40-4629-9b11-9183425bd7cf)

In console : 

![image](https://github.com/user-attachments/assets/33a2ea73-2b68-4a30-8f1d-a472e0831c8d)

**To Reproduce**
Error simply occur when "CPI Message Panel" is opened. 

**Expected behavior**
No error message

**Screenshots**

![image](https://github.com/user-attachments/assets/26ba3991-d0aa-4f9a-b02b-84edd200a538)

**Version**
Check the extension tab in your browser. E.g. 3.17.1

**Desktop (please complete the following information):**
 - OS: ![image](https://github.com/user-attachments/assets/cc6724fa-0348-49e6-84b3-cbd13e281451)
 - Browser :
 - ![image](https://github.com/user-attachments/assets/8446fc34-8867-47d3-a61d-29bcb7afb062)
 - Version: 131.0.6778.109 (Build officiel) (64 bits)

**Tenant type (please complete the following information):**
 - Neo

Thanks for your support. 
I will keep you inform if I can solve the issue (cache / network issue from somewhere)

Best Regards,
Nicolas D.

**Comment by dbeck121** [comment]
Hi @neooblaster,

we are working on a fix. Thanks for the issue!

**Comment by neooblaster** [comment]
Hello @dbeck121 ,

I saw that SAP CPI Helper has been updated on my side (but with the same version 3.17.1).
The issue seem to fixed. Indeed, the error message no longer appearing when I showing "message".

I can confirm the request is corresponding to the commit related to fix Dev #246 : 

![image](https://github.com/user-attachments/assets/3ef5d2ac-6f93-4931-8414-4040a6014d3a)

For me the issue is Solved.
I/You can close the request.

Thanks a lot for your quick resolution & for the fix :)

Best Regards,
Nicolas D.

**Comment by dbeck121** [comment]
@neooblaster 

great! It feels we still have some issues with SAP API changes but one more problem solved!

**Comment by neooblaster** [comment]
Thanks a lot for you support !
