### ISSUE TITLE
[Bug]: Trace no longer working in Google Chrome

### ISSUE THREAD

**Issue by BrettWells-FSSI** [dbeck121/CPI-Helper-Chrome-Extension#248]
When triggering the Trace log level from within the Integration Flow.
Once I trigger this operation via this plugin, then all subsequent tries via IntegrationComponent Monitor UI to set the Log Level doesn't behave properly. Although the Trace states it has activated, when sending data through the iflow the trace isn't actually activated and the log level within CPI Helper and the Integration Monitor remains set at "info".
This behavior is per iflow level, which means if plugin is used to set the Log Level for a given iflow, that iflow will behave in this manner.
![image](https://github.com/user-attachments/assets/7701cff8-65ee-4492-a44e-690924b83136)

The expected behaviour would be that the log level is at Trace status and the Inline debugging icons are available in the CPI Helper plugin
![image](https://github.com/user-attachments/assets/18e8ae89-8166-4ca6-9c3c-df07f6083371)

CPI Helper Plugin Version 3.17.1 
OS: Windows 11
Browser: Google Chrome
Google Chrome Version:  Version 131.0.6778.109 (Official Build) (64-bit)

CPI Tenant type (please complete the following information):**
 - Cloud Floundry

We did place a ticket with SAP regarding this issue and the fix they have suggested does work. SAP's reply to us is as follows;

Updated 10.12.2024 at 18:33 by SAP AgentTranslate
Info for Customer
Dear Customer,
**--Symptom--**
Log Level are set to TRACE, but when checking the artifact, the log is still on INFO mode, not TRACE.

**--Cause--**
There are some helper plugin, such as CPI Helper, installed in browser to set Log Level on Integration Flow.
Once trigger this operation via this plugin, then all subsequent tries via IntegrationComponent Monitor UI to set the Log Level doesn't behave properly.
This behavior is per iflow level, which means if plugin is used to set the Log Level for a given iflow, that iflow will behave in this manner.
**--Solution--**
Workaround: Please undeploy and deploy the iflow and check if helps, but this issue might happen again in future.
Solution: Please check if you or any member from your team is using Chrome/Edge plugin, such as "CPI Helper", and using this plugin to set the Log Level. If so, please delete the plugin from browser, after that, please ensure to undeploy and deploy the iflow again, then the behavior of Log Level will back to normal.
If you have any doubts or concerns regarding this matter, please let me know. I'd be more than happy to address any question you may have.In the meantime, if there are no further inquiries, you may consider this matter resolved, and we can close the communication on this topic.KBA : [0001239839](https://me.sap.com/notes/0001239839)  - How to close an incident - SAP ONE Support LaunchpadAlso, a survey will show up and I kindly invite you to answer it to evaluate the quality of my work.Thanks in advance and best regards,Saurabh
BTP Integrations & Foundation Services | BTP Integration Suite
SAP Support

**Comment by fippu82** [comment]
Hi Brett, thanks for the issue. We are aware of it and pushed a fix (will be in store soon). It's basically due to SAP's API changes.

**Comment by vbalko-claimate** [comment]
I already have new version of the extension - 3.17.2 (with the warning about api change), but some iflows work and some dont. Its really annoying to work without that :) You guys make great job with the helper extension. One will appreciate it only when he lost it like now :)

**Comment by dbeck121** [comment]
> I already have new version of the extension - 3.17.2 (with the warning about api change), but some iflows work and some dont. Its really annoying to work without that :) You guys make great job with the helper extension. One will appreciate it only when he lost it like now :)

Hi,

does it make a difference after you undeploy and deploy again the not working iflows? (not just redeploy)

**Comment by vbalko-claimate** [comment]
Hmmm, its weird, that I can see that trace is ok in dev tools:

POST https://<orgid>.integrationsuite.cfapps.eu10-003.hana.ondemand.com/Operations/com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentSetMplLogLevelCommand

{"artifactSymbolicName":"test_ctrlm_report_run","mplLogLevel":"TRACE","nodeType":"IFLMAP"}

![image](https://github.com/user-attachments/assets/3ad1bb76-1088-4377-9cd7-e4d12f58481f)

**Comment by fippu82** [comment]
So your Integration Content Monitoring view doesn't show the active trace, and trace is not working neither, but the response to the API call shows trace active = true? Weird indeed. I can't observe this issue anymore with 3.17.2. from my side so far...

**Comment by vbalko-claimate** [comment]
no - trace appears on the screen as active (red) as expected. Even toast message appears down there. And I checked the network traffict (screenshot up there) it seems to be ok - so on the first glance - everything is ok. But it doesnt work. When the message is triggered, no icon for trace is in messages window (that 3rd icon which triggers green/red highlight of process flow in iflow). I already tried to hard refresh page, so it would invalidate cache and reload all sources - in case that I would have old sources of extension - but no success.

Is there a way how I could say, that I`m running the last version? I can see 3.17.2 version of extension, but I saw on github, that you have several commits in that version. So maybe I dont have the last patch there.

![image](https://github.com/user-attachments/assets/6d4fe461-05f6-4704-940b-2ad6a99a39e6)

**Comment by vbalko-claimate** [comment]
no - trace appears on the screen as active (red) as expected. Even toast message appears down there. And I checked the network traffict (screenshot up there) it seems to be ok - so on the first glance - everything is ok. But it doesnt work. When the message is triggered, no icon for trace is in messages window (that 3rd icon which triggers green/red highlight of process flow in iflow). I already tried to hard refresh page, so it would invalidate cache and reload all sources - in case that I would have old sources of extension - but no success.

Is there a way how I could say, that I`m running the last version? I can see 3.17.2 version of extension, but I saw on github, that you have several commits in that version. So maybe I dont have the last patch there.

![image](https://github.com/user-attachments/assets/6d4fe461-05f6-4704-940b-2ad6a99a39e6)

**Comment by dbeck121** [comment]
@vbalko-claimate 

not really right now. But 3.17.2 is the latest version:

Ideas about this topic:

- Maybe one of your team is using another old version of CPI-Helper? 
- Do you have an Edge Integration Cell? That might be not 100% bullet proof yet. 
- Can you undeploy, wait 15 minutes and deploy again? Maybe it needs it time until it is 100% undeployed from all worker nodes...
- The reuest when you click trace button from CPI-Helper... Does it have runtimeLocationId as field? If yes, what is the content?
- Do you use a custom domain?
- What is your CPI Version? Pressing About button shows 3.70.1 for me.

**Comment by dbeck121** [comment]
> Hello, is the issue fixed in the last version of CPI HELPER ? I can't manage to make tracing work even with this last version ... (3.17.2)

It should work but you need to undeploy the iflows + deploy again. And you need to be sure all developers use at least 3.17.2

**Comment by dbeck121** [comment]
@BrettWells-FSSI and @tanguypam : Do you already have camel upgrade?

**Comment by BrettWells-FSSI** [comment]
Hi Dominic,

No we are still on version 2.24 on our Cloud Foundry tennant.

Cheers


[cid:4txuGzmy0kSimjggyOmQFwFSSIlogo_SeaGreen_RGB_resize_5_png]
        Brett Wells
Senior Software Engineer Integration
P: +64 3 353 8934<tel:+64%203%20353%208934> <tel:>
E: ***@***.******@***.***>
167 Main North Road, Christchurch ***@***.***,172.6155373,15.45z/data=!4m5!3m4!1s0x0:0x83f21f1bdb963e47!8m2!3d-43.4863573!4d172.6152563>


[cid:2oaYNs2jGU6yBBXaPvEomADigitalServicesawardbanner2_png]

**Comment by KnutliNTT** [comment]
Hi,

Just tried to undeploy the artifact under "manage integration artifacts". When i redeployed the iFlow i still don't get trace mode to work. Yesterday when I tried this temporary solution and it worked, but now I'm back to getting no trace all. 

I also have version 3.17.2

**Comment by tanguypam** [comment]
It worked for me, after undeploying and deploying it. For information, I also removed the chrome extension then re-installed it.

Thanks guys!

**Comment by dbeck121** [comment]
Ok so that is good news. There were also some updates by SAP so maybe they fixed their bug.

I guess an uninstall of CPI-Helper is not needed. Just update.

Maybe as background information:

The API to activate trace needs a new field runtimeLocationId.... If it is needed and not provided the trace will not work anymore. Nevertheless I see it as a bug that it does not return status code 400 or 500 but crashes the trace completly.

**Comment by vbalko-claimate** [comment]
Seems, that it started to work also for us. Luckily it just took some time....
But thank you again guys for great work on this tool. One will appreciate how it helps, only when it stops working.

**Comment by fippu82** [comment]
Thanks for the updates, guys! I believe SAP also fixed something by the last update on last weekend. Hopefully it's stable now again.

**Comment by dbeck121** [comment]
Hopefully solved. So I will close.  Thank you all for your support
