### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#25]
Hi, can you add feature for quick launch exact package in Disign Tab?

**Comment by dbeck121** [comment]
can you give a detailed example? I do not really know what you mean.

**Comment by methar2v** [comment]
In panel with recent flows exists Design item that redirect to design panel. Design panel has many packages, and i what to redirect to exact package.  Sorry for my bad English

**Comment by dbeck121** [comment]
Ah ok, you want to include packages in last visited? Sounds like a good idea. I will put that on my todo list

**Comment by methar2v** [comment]
Yes ;) exactly. Thnx a lot

wbr, r.velichko

ср, 3 авг. 2022 г., 02:17 Dominic Beckbauer ***@***.***>:

**Comment by madbikingcow** [comment]
Would it be possible to add a 'download' button for the actual flow being worked on, eliminating the need to go back to the package? In case the iFlow editor page is refreshed, the bread crumb path to navigate to the parent package is lost.

**Comment by methar2v** [comment]
so sad :-) it is not so important, so you can close ticket... thnx a lot for you research

**Comment by dbeck121** [comment]
Done! :-)
