### ISSUE TITLE
[Bug]: CPI Helper is running into a Problem by loading Data

### ISSUE THREAD

**Issue by RalfZi** [dbeck121/CPI-Helper-Chrome-Extension#253]
**Describe the bug**
Logs from CPI Helper
2024/11/17 13:57 > cpihelper               makeCallPromise response text:  <?xml version="1.0" ?><com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentsListResponse>
2024/11/17 13:57 > cpihelper               makeCallPromise:  GET /Operations/com.sap.it.op.tmn.commands.dashboard.webui.IntegrationComponentDetailCommand?artifactId=undefined false application/json    false
2024/11/17 13:57 > cpihelper               makecallpromisexhr 2024-12-17T12:57:42.224Z
2024/11/17 13:57 - cpihelper         164ms makeCallPromise response status:  500
**To Reproduce**

**Version**
Check the extension tab in your browser. E.g. 3.17.2

**Comment by dbeck121** [comment]
Hey @RalfZi 

we spend a lot of our free time to provide you with a free and open source tool. So at least it would be nice of you to answer the questions that are asked. 

Will close unless sufficient context is added.
