### ISSUE TITLE
Worg sort order in message pane

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#26]
Hi,

Message pane 
<img width="197" alt="image" src="https://user-images.githubusercontent.com/37860758/187042966-aa7cb635-5725-42da-8fda-55f4aeda218e.png">

Dashboard
![image](https://user-images.githubusercontent.com/37860758/187042944-8a831ad1-8afc-4221-a77c-6c4632c88217.png)

WBR roman velichko

**Comment by methar2v** [comment]
Is possible to sort log messages by ENDTIME instead of STARTTIME?
<img width="583" alt="image" src="https://user-images.githubusercontent.com/37860758/187724873-bafcf2c0-0789-457f-b7e1-0dd9761c2b4c.png">

**Comment by dbeck121** [comment]
Sorry for the late response. Sounds like a good idea. I will fix that next week after my vacation. Thanks for letting me know.

**Comment by dbeck121** [comment]
Fixed in 2.4.1

Available in a few days in Chrome
