### ISSUE TITLE
Sidebar not loading message logs for some iflows 

### ISSUE THREAD

**Issue by DennisSentler** [dbeck121/CPI-Helper-Chrome-Extension#28]
Hello @dbeck121,
In my experience on SAP CPI neo, after a first deployment of a process, messages are often not shown in sidebar. Sometimes it takes days for them to appear.
![Screenshot 2022-09-08 165314](https://user-images.githubusercontent.com/27735947/189154799-ba96dfa9-9c7a-42d4-87ac-c3bf633d78af.png)

I made some investigations:
![Screenshot 2022-09-08 165251](https://user-images.githubusercontent.com/27735947/189154791-44855307-2e48-41c2-bbe9-a8bd88b57219.png)
While loading the logs from CPI, with the function **makeCall**, there is a fixed timeout at 4s.
https://github.com/dbeck121/CPI-Helper-Chrome-Extension/blob/1777501a6d5422fcfc152f0d44ad24bc69252ef1/scripts/tools.js#L96
https://github.com/dbeck121/CPI-Helper-Chrome-Extension/blob/1777501a6d5422fcfc152f0d44ad24bc69252ef1/scripts/tools.js#L113

I have made the same call in my browser and indeed, it took longer then the defined 4 seconds. So the call for the sidebar times out and does not deliver a valid json response. As a result it is not possible to use the sitebar at all. This happens for some specific iflows only, mainly newly developed ones. 

Probably you use the **makeCall** function in other contexts as well, where it makes sense to wait only 4s. But I think for this case, it would be better, to wait even more than that.

Hopefully you can find a way around that. 

Cheers
Dennis

**Comment by dbeck121** [comment]
Hi @DennisSentler,

I did not use neo for a long time. Seems like loading times increased since then :)

I will increase the timeout. Can you try out what would be a suitable amount of time for the timeout? Maybe 6 or 8 seconds?

**Comment by DennisSentler** [comment]
I have made some tests with the problematic iflow. 
On avarage it takes ~5500ms (even there are only 14 entries). So I think 6s would be tight.

BUT, I have made some additional tests. It seems the OData query option **$orderby=LogStart desc** is making the trouble. Without the serverside ordering it takes only 50ms. The ordering increases the request time x100.

**with ordering**
![grafik](https://user-images.githubusercontent.com/27735947/189481386-b2435a7a-5aa0-4bd9-a865-d18b8f460b4e.png)
**without ordering**
![grafik](https://user-images.githubusercontent.com/27735947/189481412-4b23150c-6480-4e7a-b373-3661cead0d2c.png)

The default ordering is by LogEnd. Is that maybe also sufficent? So the still processing logs will be always on the top. Or do you think that will be confusing?
Also considering client site ordering is also an option.

**Comment by dbeck121** [comment]
@DennisSentler thanks for the investigation. That is good news because I have Issue #26 with the request to sort by end time. I guess it makes sense to show the last finished iflow at the end.

So I will change that to sort by end time (default) and two issues fixed :)

My flight goes home in a few hours so at least tomorrow I will change that and release a new version.

@DennisSentler: just for the record. Is there sth special with this iflow? High frequency maybe?

**Comment by DennisSentler** [comment]
@dbeck121 thanks great, thanks!

Unfortunatly I cannot tell what is the reason behind the longer request time for this specific iflow. Log frequency is low. Also the same iflow deployed on other cpi tenant does not cause this issue. So I guess this is internal CPI data provision problem.

**Comment by dbeck121** [comment]
Strange... Ok but nevertheless, it should be fixed with 2.4.1

I pushed the package to Google. That might take a few days until it is accepted.

Thanks for the support:)

**Comment by DennisSentler** [comment]
Issue is not resolved by the last update. Can you @dbeck121 reopen?

Why is the issue not resolved? 
The "orderby" parameter is still in place: $orderby=LogEnd desc.

Can we skip on this request parameter?
No - it seems if the orderby parameter is not set at all, there is no ordering by default. Neither on LogEnd nor on LogStart.

Example without orderby
logEnd:
[
   "/Date(1662378903640)/",
   "/Date(1662379205083)/",
   "/Date(1662648093500)/",
   "/Date(1662650823740)/",
   "/Date(1662651314546)/",
   "/Date(1662651727406)/",
   "/Date(1662651792006)/",
   "/Date(1662651851673)/",
   "/Date(1662651940930)/",
   "/Date(1662652122413)/",
   "/Date(1662652323893)/",
   "/Date(1662652513270)/",
   "/Date(1662652631306)/",
   "/Date(1661946003690)/"
]
LogStart:
[
  "/Date(1662378900630)/",
  "/Date(1662379200800)/",
  "/Date(1662648090630)/",
  "/Date(1662650820656)/",
  "/Date(1662651300736)/",
  "/Date(1662651720730)/",
  "/Date(1662651780666)/",
  "/Date(1662651840703)/",
  "/Date(1662651930600)/",
  "/Date(1662652110583)/",
  "/Date(1662652320623)/",
  "/Date(1662652500656)/",
  "/Date(1662652620593)/",
  "/Date(1661946000576)/"
]

The only solution to this problem seems to be to increase the time limit.

**Comment by dbeck121** [comment]
ok so next release has 6.5 seconds timeout. I hope that helps.

BR
Dominic

**Comment by dbeck121** [comment]
Can you confirm it works better now? @DennisSentler

**Comment by DennisSentler** [comment]
@dbeck121 sorry for the late response.
But yes, after the optimization on your part, I no longer observed this problem.

Thank you for cooperation.
