### ISSUE TITLE
New button "Download" in body tab

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#29]
Hi @dbeck121,

Welcome back from holiday.
I have made an enhancement with new button "Download" in body tab.
After you click the button, the CPI Helper will download the zip archive file of the step that you are currently viewing. It's same when you seeing it in SAP trace view, but I just made it available in CPI Helper for convenient and speedy access.
You could use this feature to backup the detail of the step for later trace or feed the zip file in to "Simulation" for debug purpose. Please see below screen recording demo.
![2022-09-12_22h38_37](https://user-images.githubusercontent.com/13759617/189656098-ad5baac1-a6b6-4758-8e47-a1f1bae98c34.gif)

**Comment by dbeck121** [comment]
That is pretty cool! I will include it in next release.

Thanks for your contributions!

**Comment by dbeck121** [comment]
Great. Actually I did not see that.

Will be part of next release!

**Comment by dbeck121** [comment]
Great. Actually I did not see that.

Will be part of next release!
