### ISSUE TITLE
CPI new host doesn't work

### ISSUE THREAD

**Issue by sapLeiYao** [dbeck121/CPI-Helper-Chrome-Extension#31]
Hi @dbeck121 ,

Our customers in China have activated a new CPI domain name, and now the plug-in does not work. Is there any domain name restriction?
Can plugins be enabled for new domains?

*-tmn.hcicn.cn1.platform.sapcloud.cn

![1664178759(1)](https://user-images.githubusercontent.com/35863969/192223751-e9f65b1a-8aa8-4b29-9e5e-1be141079671.jpg)

**Comment by dbeck121** [comment]
Hi,

i just added the domain to the allowed list. Unfortunately I have no chance to test if it works. Is there any chance that someone with access to this tenant takes the last version from dev branch, installs it as developer version and tries if it works?

**Comment by sapLeiYao** [comment]
Hi @dbeck121 ，

thanks for your reply,
I installs developer version and tries it,.
The new domain name seems to work, but the CPI page still doesn't see the button.
![e401ee9f00af26597a0618134bdfbbf](https://user-images.githubusercontent.com/35863969/192427293-4a01adde-82df-42ed-bee0-c013d20c9b13.png)
![4790a06878992fa2f9f512b0d84f134](https://user-images.githubusercontent.com/35863969/192427312-c69555a0-cb8c-478f-8d67-986133b917ef.png)
![image](https://user-images.githubusercontent.com/35863969/192427577-fb5eb2da-0c7f-436c-b648-268ce9e01038.png)

**Comment by sapLeiYao** [comment]
> Hi @dbeck121 ，
> 
> thanks for your reply, I installs developer version and tries it,. The new domain name seems to work, but the CPI page still doesn't see the button. 
-------- 
Today I switched the browser language to English, the extension is now in effect 😀😀😀

**Comment by dbeck121** [comment]
Oh really? That is strange. But only the den version or also the one from the store?

For case 1 I will release a new version :)
