### ISSUE TITLE
List of process runs is empty - 2022-10-03

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#33]
From this Monday (SAP update on w.e.?), the window with list of runs of process is empty.
Just only...

![image](https://user-images.githubusercontent.com/1871382/193830092-dbe5fafa-90df-4929-9827-d2fcd5d9fdfa.png)

these informations.

Version :  2.5.0

By Bais

**Comment by dbeck121** [comment]
Hi, 

what tenant do you use? CF or Trial account?

It seems like there is a big problem with structural changes in SAP Integration Suite.

BR
Dominic

**Comment by SAPNickYang** [comment]
Dominic,

It's integration suite (https://tenant.cfapps.eu20.hana.ondemand.com) on CF.
I didn't encounter any issue on Neo.

Regards,
Nick

**Comment by dbeck121** [comment]
fixed in 2.6.0 and small fixes in 2.6.2
