### ISSUE TITLE
New version of SCPI - cpi helper doesn't work (trial too)

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#34]
We have a new version of SCPI and CPI Helper doesn't works with it.
I noticed that on Trial version of SCPI, they update them early and it didn't work but I imagined you're working on it.
But now new version is present on normal environment and it doesn't works anymore.

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

8 October 2022 Update:

SAP Integration Suite: 6.31.*
[Update Link](https://help.sap.com/whats-new/5793247a5d5741beb0decc5b7dee1160?locale=en-US)

Bais

**Comment by SAPNickYang** [comment]
Hi Bais,

Before new version release, maybe you can still use old link to access IS on CF to do your development, which is hhttps://xxx.cfapps.xx.hana.ondemand.com/itspaces/shell/design

**Comment by SAPNickYang** [comment]
The difference between new look and original seems not that huge.
/itspaces/ has been removed from the URL of new layout.
That might lead us to a solution but then we need to think how CPI helper can detect its in which working environment Neo or CF.
![image](https://user-images.githubusercontent.com/13759617/195626382-86d8ba0b-4c5f-48e8-ae81-d74a57bb0746.png)

**Comment by dbeck121** [comment]
> 

Already working on it. I think it is just a few small bugs to fix until 2.6.0 can be released

**Comment by mlonghialtea** [comment]
2.6.0 got release, worked in new Integration Suite yesterday and now it's not working anymore (extra buttons in the editor not showing up anymore).

**Comment by dbeck121** [comment]
hi @mlonghialtea 

there seems to be another bug somewhere. It depends on the path how you go to the iFlow. Can you try to reload iFlow page if that helps?

BR
Dominic

**Comment by dbeck121** [comment]
fixed with 2.6.2
