### ISSUE TITLE
Extension Popup Not Working

### ISSUE THREAD

**Issue by santhoshvellingiri** [dbeck121/CPI-Helper-Chrome-Extension#35]
Hi,

I'm in version 2.6.1 that has release note supporting CF integration suite UI. However the Extension pop-up is not opening and below is all I see.
![image](https://user-images.githubusercontent.com/19169505/197572821-260f5a51-113c-4273-8e2e-565fbc835e29.png)

The popup open however upon clicking "Inspect  popup".

![image](https://user-images.githubusercontent.com/19169505/197573226-b769825f-ac41-4566-9026-bc7a457694d7.png)

I assume this is a issue. Please can you help fix it.

**Comment by dbeck121** [comment]
hi, 
thanks for your message.

I just released a version 2.6.2 to fix it. It takes a few days to get accepted by Google Chrome Store. So maybe tomorrow or day after tomorrow, it will work again.
