### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#36]
Hi.

Show info (see screenshot) next to (or bellow) buttons or any available placement
<img width="360" alt="image" src="https://user-images.githubusercontent.com/37860758/199700481-c8b40ffb-bb4d-4e62-acfe-aa8313a9eb31.png">

**Comment by dbeck121** [comment]
Hi @methar2v,
I checked that and it seems like it states the last version number that was deployed and not the current deployed version.

1 deploy 1.0.0
2 deploy draft

-> it will say 1.0.0 and I do not have other information from the API.

Would you still like to have this feature?

**Comment by methar2v** [comment]
so piity, please close ticket... thanx a lot for you time
