### ISSUE TITLE
Suggestion way of showing plugin

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#39]
Hi @dbeck121 ,

I am developing a plugin for CPI Helper and understood the rule of plugin is to open its content in a new tab but not inside CPI Helper. I would like to seek any opportunity/suggestion to make the plugin content to be part of CPI Helper. Such as, the plugin can be rendered as another tab next to Plugins, or under Plugins tab.

Because, there is a auto refresh in the background in Messages to update status of messages. As a result, anything you enter inside the popup will be reset in next auto refresh.
![image](https://user-images.githubusercontent.com/13759617/202902214-96fbf808-ecb7-42e0-8804-920cfc0fad82.png)

![2022-11-20_23h39_31](https://user-images.githubusercontent.com/13759617/202902364-29b5b0b6-6fbe-48a7-9268-015527fad482.gif)

Thanks.

**Comment by dbeck121** [comment]
Hi @SAPNickYang 

I could try to change the popup not to refresh the plugin content if that helps you?

That could be a quick fix. And I can try to add the big popup function to plugin so you can create your own screen. Would that help? 

Of course we could also extend the header bar to show a button for you but the function where it would be placed is very old and fragile...

BR

**Comment by dbeck121** [comment]
Hi @SAPNickYang 

I extended the plugin features a bit. Please have a look at the example plugin on dev branch. Dev branch is currently for testing chrome manifest v3. Before switching to dev branch, save manifest.json and overwrite it again after dev checkout.  This means v2 is still used and the hot reload feature does work.

I added "static" parameter that prevents reloading and a function to show a popup.

**Comment by SAPNickYang** [comment]
@dbeck121 ,
Thank alot for your adjustment.
I will use dev branch for my plugin development.

**Comment by dbeck121** [comment]
I am curious... What is the AI Coding Buddy?

**Comment by SAPNickYang** [comment]
@dbeck121 I am excited to inform you that the initial stable version of my plugin is now available and ready for push to your repository. Developers will need to provide their OpenAI API key in order to use it. Please take a look at the below screen recording for a quick preview. I would greatly appreciate it if you could make changes to the plugin when I push it to the dev branch or another branch.
![2022-12-08_20h02_11](https://user-images.githubusercontent.com/13759617/206404945-d1a85c4c-1cf5-4a4b-bf55-5b64d8ac8644.gif)

**Comment by dbeck121** [comment]
Looks pretty cool :) I am looking forward to try it.

Would you ad an explanation what it does to the readme? Or maybe we can create a blog post to the SAP community

**Comment by SAPNickYang** [comment]
> Looks pretty cool :) I am looking forward to try it.
> 
> Would you ad an explanation what it does to the readme? Or maybe we can create a blog post to the SAP community

Just push my code to dev branch. Do I need to push it to main branch as well? Or you will promot it to main branch and then release to the public? I have made an wiki page in my Github. Same content will be publish from my LinkedIn and SAP community. Cheers.

**Comment by SAPNickYang** [comment]
@dbeck121  Just applied changes in my main branch and some changes from your end in plugin loader is yet to be available in main branch. I guess your changes also need to be applied to main branch then this plugin can work.
![image](https://user-images.githubusercontent.com/13759617/206885064-ad7b7384-e529-4381-88be-cfc7456e6791.png)

**Comment by dbeck121** [comment]
Hi, 

looks great! 

you said you have a wiki, shall we link it directly in your plugin so that people have a manual directly?

The plan was to release it early but I got a sponsor who gives me the oportunity to work on CPI Helper and do things I always wanted, but had no time. So I am changing overall design a lot right now.

Release should be before Christmas with Version 3 including your plugin, new design, some new features etc.

Btw: your plugin looks great with the new design. You can pull my dev to have a glimpse. Also I got back to manifest v2 so that auto reload works again.

**Comment by SAPNickYang** [comment]
Hi @dbeck121 ,

Yes, the link of wiki page is here, [https://github.com/SAPNickYang/CPI-Helper-Chrome-Extension/wiki/CPI-Helper-Plugin---My-AI-Coding-Buddy](https://github.com/SAPNickYang/CPI-Helper-Chrome-Extension/wiki/CPI-Helper-Plugin---My-AI-Coding-Buddy). I put the link in the plugin description as well as a blog on SAP community, the link of the blog is here https://blogs.sap.com/2022/12/13/how-i-use-ai-models-from-openai-in-my-sap-ci-is-development/.

New look&feel looks awesome! Great work!
Looking forward to seeing new release coming to Google web store.
