### ISSUE TITLE
Undeploy button from info box to main menu

### ISSUE THREAD

**Issue by robertfels** [dbeck121/CPI-Helper-Chrome-Extension#4]
I'm thinking about whether it might make sense to drag the "undeploy" button from the Info modal to the main menu. We need it very often.
But then there should be maybe a modal that asks again if you really want to undeploy - just to be on the safe side.
What do you think?

**Comment by dbeck121** [comment]
I have never really used the undeploy button but shift this to the main menu should be no problem. The modal makes sense.

I will put it on the todo list for the next versions.

In general I was thinking to take Trace, Logs, (Undeploy) and Message button from Menu to the message PopUp/Sidebar and always show the sidebar. What do you think about that? Then we get rid of the refresh problems in the menu.

**Comment by robertfels** [comment]
Also a great idea. Lets discuss this in our upcoming call

**Comment by dbeck121** [comment]
Part of undeploy plugin now
