### ISSUE TITLE
Plugin donot load in the new unified integration suits web UI

### ISSUE THREAD

**Issue by saurabhkabrahenkel** [dbeck121/CPI-Helper-Chrome-Extension#41]
Hi,

With the new UI for SAP integration suit where all products are accessible/managed from a single URL, the add-in for CPI Helper is not laoding. See the attached image.

I believe, it is due to the URL change between the existing UI(where addin works) vs the new unified UI(where addin doesn't work)

OLD UI Url:
https://XXXX.it-cpitrial03.cfapps.ap21.hana.ondemand.com/itspaces/shell/design/contentpackage/TestSK/integrationflows/Access_Credentials

New UI Url:
https://XXXX.integrationsuite-trial.cfapps.ap21.hana.ondemand.com/shell/design/contentpackage/TestSK/integrationflows/Access_Credentials

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/99563007/207836894-cd0314f2-4098-484d-9977-455ff7f1ad93.png">

can you please check this?

**Comment by dbeck121** [comment]
Hi,

I took the url already in account. It works for me. Sometimes it needs a refresh. Does it also not work after pressing F5?

BR

**Comment by saurabhkabrahenkel** [comment]
Seems something was wrong with my machine...despite trying multiple refresh it dint load earlier but now this seems to work.
Sorry for the trouble and Thanks for quick support.!
