### ISSUE TITLE
3.0.0 version out of memory

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#42]
with new update to 3.0.0 it very often see "OUT OF MEMORY" in chrome/edge/mozila ;-(

**Comment by methar2v** [comment]
![image](https://user-images.githubusercontent.com/37860758/208477355-fe685a4f-7849-4b97-aa06-6188c94963c2.png)

and memory consumption is still inscreases

**Comment by dbeck121** [comment]
It seems to be a problem with jquery. I. updated it and it runs way smoother now. I uploaded it to chrome store and hopefully tomorrow it will be accepted and shipped to the browsers.

BR
Dominic

**Comment by dbeck121** [comment]
can you confirm that it is better with 3.0.1?

**Comment by methar2v** [comment]
Yes, "out of memory" error is gone
