### ISSUE TITLE
3.0.1 version, tabs not clickable (links, info etc)

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#43]
![image](https://user-images.githubusercontent.com/37860758/208604795-9e699a2f-2762-4760-bc78-7b7215a0dc6b.png)
![image](https://user-images.githubusercontent.com/37860758/208604822-6c6bc1d5-376b-4eba-bdda-273f42afd769.png)

cant click on tabs ;)

**Comment by dbeck121** [comment]
3.0.2 is on its way. Thank you!
