### ISSUE TITLE
3.0.2

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#44]
:-) Here's Johnny!  (c) The Shining (1980)

no new recent items is added to storage, after clear storage and start chrome/edge in private mode - no recent flows|packages etc is adding to recent list

![image](https://user-images.githubusercontent.com/37860758/208742587-9f5e3e3a-31b5-4445-97dd-82f60aa85101.png)

**Comment by dbeck121** [comment]
oh :-D I did rename the jquery file. Fixed in 3.0.4!
