### ISSUE TITLE
Fonts are too small when the extension is enabled.

### ISSUE THREAD

**Issue by harishannamalai** [dbeck121/CPI-Helper-Chrome-Extension#46]
Hi, 

I had enabled the Extension in my Chrome Browser and used the extension version 2.7.0.
Everything was good, however when I upgraded to version 3.0.2, all the Fonts became a bit small. When I disable the Extension, the font size returns to normal.

The Package Page, Artifacts Table Page had small fonts with large spaces. 

The problem is exacerbated in High resolution monitor and Fractional Scaling.

I use this Helper in my work, and I am unable to source a screenshot.

**Comment by dbeck121** [comment]
Hi,

thanks for the message. I did not recognize this. Maybe my screen is not to big to see it. 

I try to fix it in the next version. 

Can you make a list where this happens so that I can find it even without a screenshot?

BR

**Comment by harishannamalai** [comment]
Hi, 

Thanks for having a look at this issue. I tried to get my own trial licence to capture the issue, Unfortunately wasn't successful.

The issue is clearly observable in:

1. When you open a package and Navigate to "Artifacts" Tab.
2. The fonts for names of the Iflows and description of the Iflow are very small with disproportionate amount of Gap between the name and description.
3. When you navigate to the Deployed Iflows in Manage Integration Content Section, the Left Side Nav Bar has the same issue as described in point 2.
4. In Iflow designer, when you select any flowstep, the Menus fonts are very small.

When the extensions are disabled, the Fonts appear of Normal Size.

These are not serious enough to stop anyone from using. But the issue takes away the pleasure of using the extensions.

**Comment by dbeck121** [comment]
I guess I fixed the issue. Will be part of next release!

**Comment by dbeck121** [comment]
@harishannamalai problem fixed?

**Comment by harishannamalai** [comment]
I just updated my extension to 3.07 and the issue is resolved.
Much thanks.
