### ISSUE TITLE
Porting to Firefox

### ISSUE THREAD

**Issue by archetypon** [dbeck121/CPI-Helper-Chrome-Extension#48]
Hi,
I'd like to contribute porting the extension to Firefox: what could be a proper way to do so?
My ideas are:
- splitting the repo in 2 subfolders
- create a new project

What do you think?

Thanks.

**Comment by dbeck121** [comment]
Hi, thanks for your contribution. It seems like that Chrome and Firefox Extension API is very similar.

Did you try to run it as it is on Firefox? If that works we have one codebase for the plugin.
If not, i think it would be nice to adapt the code that we have multi platform app:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

That would mean for you to fork it and create pull requests for changes. If that is not working I guess I would go with two projects.

Keep me in the loop about your progress if you want. 

BR

**Comment by archetypon** [comment]
I did some test and is almost everithing portable (there are just few issues that I think can be maintained as compatible across browser). I'd go with the fork: I'll keep you in the loop.

**Comment by dbeck121** [comment]
sounds good!

**Comment by dbeck121** [comment]
done. Please check comments in pull request. Thanks a lot.

https://addons.mozilla.org/de/firefox/addon/cpi-helper/
