### ISSUE TITLE
Plugin setting type "checkbox" is not handling correctly in plugins.js

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#49]
When using the "checkbox" setting type in the plugin settings declaration, the code in plugins.js does not correctly read the value back and the text attribute is not displayed as a label after the checkbox.

**Comment by dbeck121** [comment]
:-) Thanks for the contribution. Will be part of next release!

**Comment by dbeck121** [comment]
released!
