### ISSUE TITLE
Recently opened iflows are no longer saved

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#5]
Greetings.
Recently opened iflows are no longer saved. And no data stored in local chrome/edge storage

**Comment by santhoshvellingiri** [comment]
Yes. I no longer see it too. That made us click lot less to open the recent Iflow. Would love to have it back soon :)

**Comment by dbeck121** [comment]
Thanks for open this issue. 

Seems I messed sth up together with the new button to show message sidebar always on startup.

Will be fixed in 2.0.2 arriving the next week.

**Comment by santhoshvellingiri** [comment]
Thank you @dbeck121 :)
