### ISSUE TITLE
Enhancement in Simple Notepad

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/CPI-Helper-Chrome-Extension#51]
I have made enhancements to the Simple Notepad plugin for CPI Helper users. Now, users have the option to enable data encryption to protect any data entered in the notepad. Once the user has ticked the "Encrypt when saving data" option, they will be prompted to enter a password during the data-saving process. This password will be used to encrypt the content to protect the data.
![image](https://user-images.githubusercontent.com/13759617/223734612-b76848c1-ed30-490c-b72e-ab2d2ddb5350.png)

![image](https://user-images.githubusercontent.com/13759617/223735246-50393a23-b9d3-489d-b246-c2864d1ffe24.png)

When the user reopens the plugin, they will be required to enter the password to decrypt the content. If they fail to enter the correct password, the encrypted content will be displayed in the text area.
![image](https://user-images.githubusercontent.com/13759617/223735686-1a43de8e-7f92-4ae8-bd1f-8f15537b8ceb.png)

**Comment by dbeck121** [comment]
That looks great! It is super nice of you to contribute to CPI Helper again  :-)

I will check and it will be part of next release!

**Comment by dbeck121** [comment]
released
