### ISSUE TITLE
UI of overlay are unbounded.

### ISSUE THREAD

**Issue by zex3d** [dbeck121/CPI-Helper-Chrome-Extension#54]
Hello,

Issue:
1. It a chore to remove and move around this overlay. There is no way to minimize the overlay. When developing multiple deployments is necessary, not when creating I-flow logic (or moving it without removing it). Once we delete it, the only way to return is to reload.
2. When we resize, or split screen overlay remain in same left space due to declaration in "px". Many time it move outside of window. We are also able to move overlay outside of window. which sometimes we can't revert to position unless tab is reloaded.

for issue 1:
![image](https://user-images.githubusercontent.com/87596092/230797026-2f202cd8-e567-4bfa-8396-26a487a48db1.png)overlay design.

for issue 2:
![image](https://user-images.githubusercontent.com/87596092/230797052-7e13cce1-b525-42f1-843a-25440ca8ca13.png)

Resolution:

1. It can be reduced when we click on "CPI Helper". If we click it again then maximize which comes as default. (My personal preference is a header color that matches the outer custom color we choose)
2. overlay header can be bounded by window space and relative spacing instead of fixed.

first time creating a pull request. Let me know if overlay design was intended.
Thanks, Om

**Comment by dbeck121** [comment]
Hi, thanks for your contribution. Unfortunately pull request is closed. So I can not accept or try. 

Br
