### ISSUE TITLE
CPI Helper is not available on Firefox browser

### ISSUE THREAD

**Issue by liangzihua** [dbeck121/CPI-Helper-Chrome-Extension#57]
Hi,
Can this plugin only be used on Chrome browsers? After installing this plugin on the official website of Firefox, the CPI helper is not working.
<img width="1136" alt="图片" src="https://user-images.githubusercontent.com/57387713/232260547-67333e10-bf76-4021-a107-fb177adb50b4.png">

<img width="1147" alt="图片" src="https://user-images.githubusercontent.com/57387713/232260563-27e5d9f8-1b9a-4477-a95c-dd57775f2a56.png">

I tried Chrome browser again. Since I cannot access the Chrome store, I have to get the add-on from github:https://github.com/dbeck121/CPI-Helper-Chrome-Extension. However, when you load it into Chrome, I receive the error："Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details ".
<img width="686" alt="图片" src="https://user-images.githubusercontent.com/57387713/232260818-6b4d2326-ada8-49bb-afbe-5a2867dfb46a.png">
<img width="952" alt="图片" src="https://user-images.githubusercontent.com/57387713/232260825-cd1ceb6f-ef68-4a39-8ec3-d5f298826982.png">

**Comment by dbeck121** [comment]
Hi,

thank you for your message. Let's try to find out what is going wrong with your installation.

In general the plugin works great with Chrome, Edge and also Firefox and I checked but it works with all my tenants. 

You are using a standard trial account right?

Chrome:
you can ignore the warning message about manifest v2. It is (yet) still supported and should have no influence. Your screenshot at least shows that CPI helper is activated. Can you check if it shows up on your CPI tenant in Chrome?
If yes, there might be a problem the Firefox version of the plugin.

Firefox:
The support for Firefox is very new and in beta. Nevertheless it should work. 

I can think about 2 potential problems:
- your language settings. Could you try to set default to English and try again?
- maybe your company limits browser extensions with a group policy
- your tenant name

So maybe you can check the following:

1. Download the newest version here from Github like you did before. I updated some files. Maybe that helps already.
2. Ignore the message in Chrome and see if it works. 
3. Switch your language settings to English,/ restart the browser (Chrome and Firefox) and try again.
4. You can open developer tools in Chrome and check the 'console' tab for errors, when loading CPI iflow designer. If you could post screenshots of it here, that would be great. 
https://developer.chrome.com/docs/devtools/open/

My main guess is that the plugin might have problems with Chinese characters. I develop this plugin for free in my spare time and sap does not support me so these are cases that I can not test my self and I am happy about comments from people like you that helps everyone to make CPI helper better.

BR
Dominic

**Comment by liangzihua** [comment]
Hi,
    Thank you very much. After change the language of browser (Firefox and Chrome) to  English, it is working OK.
    
 Firefox is  working OK.
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/57387713/232280260-8bfff1f7-cf80-4b56-8e57-6114df73c9ff.png">

Chrome have two errors, but it is working ok.
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/57387713/232280282-cee4e03a-bc68-424a-ae4f-03041ba93781.png">

**Comment by dbeck121** [comment]
Great to hear! that will help others as well in the future. I will try to find some time to investigate why Chinese language made problems.

It would be great if you could create/change a positive review in firefox store that it works :-)

Have a nice weekend
Dominic

**Comment by dbeck121** [comment]
Good news. I might have found the error. I pushed the newest version to github for chrome. If you like you might check if CPI Helper works now when using Chinese als default language.
