### ISSUE TITLE
Auto open of Helper doesn't always work

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#58]
The message side bar doesn't automatically reopen after navigating from an IFlow back to the package and then back to an IFlow again.

**Comment by fippu82** [comment]
pull request created: https://github.com/dbeck121/CPI-Helper-Chrome-Extension/pull/59

**Comment by dbeck121** [comment]
Great! Thank you so much. I will check it the next week and it will be part of next release probably!
