### ISSUE TITLE
Header color not always set

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#66]
When navigating back to the Package and then back to an Iflow, or when opening a script (an Iflow resource), the title bar is not set to the configured color anymore.
Reason is that the interval in function setData (identify-tenant.js) is only set once at the initial load of the Extension or page. These page changes however are done via Ajax (or similar) and do not trigger a page reload. 
We need to trigger the interval for color etc. updates (identify-tenants.js) when in function checkURLchange() of contentScript.js as well.

**Comment by dbeck121** [comment]
@fippu82: you changed the interval right?

It feels like it is working way better now. If that has still problems, we can check every x seconds for all the time if the page color changed.
