### ISSUE TITLE
Escalated Status should be displayed with different icon

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#69]
For escalated messages, there is still a green checkmark displayed in the sidebar. This should be changed into the same as the error status or a different one that represents the escalated status.

**Comment by dbeck121** [comment]
I added a #ff8300 ? icon for next release. What do you think? For me it is not really red but different. But I do not use escalation end often.

**Comment by fippu82** [comment]
Looks great! Already helped me today. Escalation status is quite important for me as it shows in the log that an error occurred that got handled in some way.

**Comment by dbeck121** [comment]
released in new version
