### ISSUE TITLE
Tooltip or popup resize  needed

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#7]
Hi, can you add resize options (or horizontal scroll) to this popup or tooltip for some iflow longnames?

<img width="238" alt="image" src="https://user-images.githubusercontent.com/37860758/166632947-0cf204c6-fc85-4b62-8db0-7edc7d86b49f.png">

**Comment by dbeck121** [comment]
popup is now bigger.
