### ISSUE TITLE
Title and configuration pop-up windows disappears

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#8]
Hi I've notice now that the windows with tab label edit and color selection with useful links doesn't show up again.
Is it normal?
![image](https://user-images.githubusercontent.com/1871382/168059810-0d456d6b-4b02-4275-b0b2-8c384107f614.png)

**Comment by bdbais** [comment]
any news about this problem? I can't see property window..

**Comment by dbeck121** [comment]
it works for me. It is only showing up when you are in design view of an iflow.

**Comment by bdbais** [comment]
Okay, I removed the extension and I reinstall it again, now it works.
