### ISSUE TITLE
Inline debug not working @latest cpi helper verison

### ISSUE THREAD

**Issue by methar2v** [dbeck121/CPI-Helper-Chrome-Extension#82]
Hi.

<img width="1101" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/37860758/c373a6b9-cae0-48f6-8dfc-79a7088fb4b0">

**Comment by dbeck121** [comment]
oh no... refactoring error. Will be fixed asap in 3.6.1

Thanks for the issue!

**Comment by dbeck121** [comment]
3.6.1 released

**Comment by methar2v** [comment]
Thnx a lot

wbr, r.velichko

пн, 21 авг. 2023 г., 22:28 Dominic Beckbauer ***@***.***>:
