### ISSUE TITLE
CPI-Helper has run into a problem while catching X-CSRF-Token

### ISSUE THREAD

**Issue by daMuho** [dbeck121/CPI-Helper-Chrome-Extension#83]
My  CPI helper keeps on showing me this error and stops me in using it. The browser I use is chrome.
![2023-08-21_16-01-11](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/72600657/0825b2fa-3802-40b2-bb2e-2294f9408b96)

**Comment by daMuho** [comment]
The issue solved when I update Chrome...

**Comment by daMuho** [comment]
Hi Dominic,

Thanks for your support. First I thought it was resolved after updating
chrome. Now it comes back again. I tried reinstalling it, but the error
still persists. Do you want me to open the issue again on github? Also the
funny thing is, I don't encounter this in Microsoft Edge.

Many thanks,

Roderick M. Aring

**Comment by dbeck121** [comment]
If it is still not working, please create a debug log and send to [dxbdyuofm@mozmail.com](mailto:dxbdyuofm@mozmail.com) mail. I will have a closer look than.

From docs:

Trace Mode or other features are not working. Is there a debug mode?
In case of problems, you can contact me and send a debug log. You can activate the debug log while visiting an deployed IFlow, extend the url with ?cpihelper_debug=true&cpihelper_debug_download_duration=60000 and press enter to load again. Try to reproduce the error and after 60s, the debug log will download automatically. Send this to me via mail or linkedin.

Example url: https://xxxxxtrial.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com/shell/design/contentpackage/test/integrationflows/test?cpihelper_debug=true&cpihelper_debug_download_duration=60000
