### ISSUE TITLE
Trace not working

### ISSUE THREAD

**Issue by girisgc** [dbeck121/CPI-Helper-Chrome-Extension#84]
Hi, up to last update, Inline Trace was working fine, but from recent update Inline Trace is not working and even when I click on the Inline Trace, it is not opening. 
Also, when I keep Trace ON, the entire system is slowing down and Chrome gets crash most of the times.

**Comment by dbeck121** [comment]
Hi, are you running version 3.6.1 or 3.6.0?

**Comment by girisgc** [comment]
3.6.1, updated today

**Comment by girisgc** [comment]
It is working sometimes and sometimes not

**Comment by girisgc** [comment]
Inline Trace for debugging is not working properly

**Comment by dbeck121** [comment]
Hi,
anything else that is not working? Which Browser are you using? And finally Neo or CF?

**Comment by dbeck121** [comment]
If it is still not working, please create a debug log and send to dxbdyuofm@mozmail.com mail. I will have a closer look than.

From docs: 

**Trace Mode or other features are not working. Is there a debug mode?**
In case of problems, you can contact me and send a debug log. You can activate the debug log while visiting an deployed IFlow, extend the url with ?cpihelper_debug=true&cpihelper_debug_download_duration=60000 and press enter to load again. Try to reproduce the error and after 60s, the debug log will download automatically. Send this to me via mail or linkedin.

Example url: https://xxxxxtrial.integrationsuite-trial.cfapps.us10-001.hana.ondemand.com/shell/design/contentpackage/test/integrationflows/test?cpihelper_debug=true&cpihelper_debug_download_duration=60000

Please send me the debug log and answer the following questions:

What is the url of the Cloud Integration Tenant?
Trial Account?
Custom URL?
Neo or Multicloud?
Does the error occur all the time or only sometimes.

**Comment by girisgc** [comment]
> Hi, anything else that is not working? Which Browser are you using? And finally Neo or CF?

Using Chrome Version 116.0.5845.111, and it is for Integration Suite 6.41
It is not trail account, my company tenant, error occurs all the time by showing a popup like "CPI HELPER RUN INTO A TIMEOUT"

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/17080975/b69b92a1-9f46-4277-ae76-55c9b28c5b86)

**Comment by girisgc** [comment]
All these days it was working fine, but from recent update it is not working

**Comment by dbeck121** [comment]
The only thing that I can think about is that your company has a package filter or a Chrome security feature so that packages were filtered and timeouts occur.

**Comment by girisgc** [comment]
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/17080975/fefa579e-73ac-4bde-800e-0ffc1b238276)

**Comment by girisgc** [comment]
it is showing not found when i try to use the debug link

**Comment by dbeck121** [comment]
that should not happen... can you send me the url of your IFlow via Mail:[dxbdyuofm@mozmail.com](mailto:dxbdyuofm@mozmail.com)

**Comment by dbeck121** [comment]
But if it sometimes works and sometimes not... could it be that you really have a bad internet connection? Maybe you can send me a speedtest like

<img width="714" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/54773577/dc008440-e215-4b55-b384-bf0f7a8ef700">

from https://www.speedtest.net/

If your ping is very high. This would explain it.

**Comment by girisgc** [comment]
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/17080975/d4473a7b-c834-4959-948a-fa07ef983ecf)

**Comment by girisgc** [comment]
Speed is very good

**Comment by girisgc** [comment]
Check your email

**Comment by dbeck121** [comment]
I responded to you. The url was mixed up and I sent you the (hopefully) right one. This one should word to get the logs.

**Comment by dbeck121** [comment]
I do not see any problems in the logs... the error happened during the 60 seconds? Maybe I have to extend the logs a little bit...

**Comment by fippu82** [comment]
@dbeck121 I see the same issue sometimes since the update to 3.6.0/3.6.1. I tried to reproduce it and believe it mainly happens when opening large Iflows on a slower machine that has already high CPU load. The debug log doesn't include the timeout, but I will send it to you via email. 
I guess something in the timeout handling has changed since the refactoring. Could we just increase the timeout to avoid this message on slower PCs?

**Comment by dbeck121** [comment]
@fippu82 I improved debug log especially for timeouts in version 3.6.2 (github pull for you I guess :-) )

could you
1. check in Chrome Dev Tools how long calls in large IFlows take (in message tab)
2. Check in 3.6.2 if timeout still occurs (timeout now 5 seconds)

**Comment by fippu82** [comment]
Seems it has helped! So far I couldn't reproduce the timeout anymore.
