### ISSUE TITLE
Idea:  performance stats

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#88]
When you have all start-stop-duration of a run could you add a performance visualization on steps, like 3 numbers on top:  min-avg-max time?
Or change a colorbar with red to green temperature visualization, red is slowest steps (avg calculation) and blu medium, green fast.

**Comment by dbeck121** [comment]
Sounds good. Time is the limiting factor but I will put it on the backlog

**Comment by incpi** [comment]
Color states time consumed.  any suggestion please.
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/87596092/b105c1ac-411d-4cb4-ab95-680418dc1920)

~~Op1.  Keep it kind of height map~~ Confusing color and crashing under large integration.
Op2. Keep limited height map
Op3. Above. 5 stage color map
Op4. Keep only min max

**Comment by dbeck121** [comment]
Thanks to @incpi available as plugin!
