### ISSUE TITLE
Improvements: Variable management

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#9]
Is it possible to put a little windows under normal (with a switch off-on button) with variables, local and global and delete - view capability?

**Comment by robertfels** [comment]
@bdbais you can find these variables in "info"

**Comment by bdbais** [comment]
I'm trying to create a list of local and global variable with delete or preview window.

**Comment by dbeck121** [comment]
but what is the different to the info view?
