### ISSUE TITLE
Trace button, does not work anymore on (some) CF and Neo

### ISSUE THREAD

**Issue by DennisSentler** [dbeck121/CPI-Helper-Chrome-Extension#94]
Hello,

I have discovered, that the "trace" button, which is rendered by the CPI helper, does not work anymore, on any Neo tenant I could try it on. And on some CF tenant it works, and on some it does not. 

Logs; CF; Integration Suite; Partner Subscription Model:
Status 302
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/27735947/2de7f80c-8201-4960-a49b-c3faa41384b9)

Logs; CF; Integration Suite; Full Subscription Model:
Status 200
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/27735947/44af7ba6-d493-4600-9598-4aae48b1c9a8)

Logs; Neo; Cloud Integration; Full Subscription Model:
Status 403
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/27735947/4a368e26-c106-469c-acd4-2311163f2646)

If you need more information, let me know. 

BR
Dennis

**Comment by dbeck121** [comment]
Strange... they must have changed the link structure again.... 

It works on tenants with integration Suite in its name but not on tenants with the old link structure. It is probably because of the "itspaces" in the url

Did this start with the new version 3.7?

**Comment by veraciousnottaken** [comment]
> Did this start with the new version 3.7?

Yes

**Comment by dbeck121** [comment]
ok problem found and fixed. I uploaded 3.7.1 to Chrome store and it will be available Monday or Tuesday I guess.

Thanks for the help and patience.

**Comment by octavonu** [comment]
Hi,
first of all, thank you for your great work. Your extension is just great.
 
I can enable the trace, unfortunately the T(race) payload is not visible in the message tab anymore.

Thank you

![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/50553626/a4ba0e05-a05d-4b4a-8108-5a74133fbe21)

**Comment by dbeck121** [comment]
fix in 3.7.1 coming soon

**Comment by veraciousnottaken** [comment]
3.7.1 works fine for me, thank you!

**Comment by dbeck121** [comment]
Works now!

**Comment by DennisSentler** [comment]
Works for me as well, thank you @dbeck121!
