### ISSUE TITLE
Request:  remove anoying "flying error dialog"

### ISSUE THREAD

**Issue by bdbais** [dbeck121/CPI-Helper-Chrome-Extension#95]
Could you please transform in button the result icon, so we can click on it and open error dialog and close it only when it need, every time we move on this icon a big dialog windows with a long delay to disappears occupied all screen.

**Comment by dbeck121** [comment]
The dialogue is not really useful for large messages.

I work on CPI-Helper for free and do not have much time. So these improvements have low priority. But it is on the list.

**Comment by dbeck121** [comment]
Will be part of next release!
