### ISSUE TITLE
Messages are not listed because of the timeout configuration 

### ISSUE THREAD

**Issue by sait-gun-acorel** [dbeck121/CPI-Helper-Chrome-Extension#97]
Hi All,

Recently I started to encounter empty message panes. When I checked the network section in the developer tools, requests were canceled due to the 5-second timeout limit. 

If I increase the timeout to 10 seconds by manually modifying tools.js@135 line, the messages start to show again. It might be a good idea to make this timeout configurable by us via the settings section of the extension.

<img width="1761" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/118972569/e15a9d15-c24b-4429-9b6f-285772fe9b99">

Thank you,

**Comment by sait-gun-acorel** [comment]
Hi Dominic,

I am using 3.6.2. I think that's the latest version is available in Edge Store. 

<img width="1323" alt="image" src="https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/118972569/83fc0ba4-f769-40e3-ba1d-70df6a079c56">

**Comment by dbeck121** [comment]
Edge Store takes really long to adopt new versions. But I guess it will arrive this week. 3.7.1 is in store review
